# Generated by Django 2.0.4 on 2018-04-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dronestream_id', models.CharField(max_length=80, unique=True, verbose_name='Datastream ID')),
                ('number', models.BigIntegerField(unique=True, verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('narrative', models.CharField(max_length=255, verbose_name='Narrative')),
                ('deaths_min', models.IntegerField(blank=True, null=True, verbose_name='Deaths (min)')),
                ('deaths_max', models.IntegerField(blank=True, null=True, verbose_name='Deaths (max)')),
                ('civilians_min', models.IntegerField(blank=True, null=True, verbose_name='Civilians (min)')),
                ('civilians_max', models.IntegerField(blank=True, null=True, verbose_name='Civilians (max)')),
                ('injuries_min', models.IntegerField(blank=True, null=True, verbose_name='Injuries (min)')),
                ('injuries_max', models.IntegerField(blank=True, null=True, verbose_name='Injuries (max)')),
                ('children_min', models.IntegerField(blank=True, null=True, verbose_name='Children (min)')),
                ('children_max', models.IntegerField(blank=True, null=True, verbose_name='Children (max)')),
                ('tweet_id', models.BigIntegerField(blank=True, null=True, verbose_name='Tweet ID')),
                ('bureau_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bureau ID')),
                ('bij_summary_short', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Bureau of Investigative Journalism Summary Short')),
                ('bij_link', models.URLField(blank=True, null=True, verbose_name='Bureau of Investigative Journalism Link')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('names', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Names')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country', verbose_name='Country')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Strike',
                'verbose_name_plural': 'Strikes',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
            },
        ),
        migrations.AddField(
            model_name='strike',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Town', verbose_name='Town'),
        ),
    ]
